#!/bin/bash

# Script na získanie externej Railway URL
# Tento skript pomôže získať externú URL pre lokálny vývoj

echo "🔗 Railway Externá URL Guide"
echo "============================="
echo ""
echo "Tvoja aktuálna DATABASE_URL používa internú Railway URL:"
echo "  postgres.railway.internal:5432"
echo ""
echo "Táto URL funguje LEN v Railway prostredí, nie z tvojho počítača!"
echo ""
echo "📋 Ako získať externú URL:"
echo ""
echo "1. Otvor Railway Dashboard:"
echo "   https://railway.app"
echo ""
echo "2. Vyber svoj projekt a PostgreSQL databázu"
echo ""
echo "3. Klikni na záložku 'Connect' alebo 'Variables'"
echo ""
echo "4. Nájdi 'Public Network' alebo 'Public URL'"
echo ""
echo "5. Skopíruj connection string"
echo ""
echo "6. Pridaj na koniec: ?sslmode=require"
echo ""
echo "7. Aktualizuj .env súbor:"
echo "   DATABASE_URL=\"postgresql://postgres:PASSWORD@HOST.proxy.rlwy.net:PORT/railway?sslmode=require\""
echo ""
echo "💡 Tip: Môžeš vytvoriť .env.local pre lokálny vývoj"
echo "   a nechať .env s internou URL pre Railway production"
echo ""
echo "📖 Viac informácií: pozri RAILWAY_URL_GUIDE.md"
echo ""
